"""
샘플 데이터 (테스트용)
======================
실제 Steam 리뷰 데이터와 동일한 형식의 샘플입니다.
개발/테스트 시 Steam API 대신 이 데이터를 사용할 수 있습니다.
"""

SAMPLE_GAME_INFO = {
    "app_id": "2621690",
    "name": "Arc Raiders",
    "type": "game",
    "developers": ["Embark Studios"],
    "publishers": ["Embark Studios"],
    "release_date": "2025년 10월 30일",
    "header_image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2621690/header.jpg",
    "short_description": "Arc Raiders는 3인칭 협동 액션 슈터 게임입니다."
}

SAMPLE_REVIEWS = [
    {
        "review_id": "1001",
        "language": "korean",
        "language_name": "한국어",
        "review_text": "전투 시스템이 정말 재밌어요! 총 쏘는 느낌이 타격감 있고, 협동 플레이가 잘 되어 있습니다. 다만 콘텐츠가 좀 부족한 느낌이에요. 업데이트 기대합니다.",
        "recommended": True,
        "votes_up": 45,
        "votes_funny": 2,
        "playtime_total_hours": 67.5,
        "playtime_at_review_hours": 45.2,
        "created_date": "2025-11-10 14:30:00",
        "timestamp_created": 1731250200,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1002",
        "language": "english",
        "language_name": "English",
        "review_text": "Great gunplay and movement system! The graphics are stunning. However, the game needs more content and the matchmaking can be slow sometimes. Still worth playing with friends.",
        "recommended": True,
        "votes_up": 120,
        "votes_funny": 5,
        "playtime_total_hours": 89.3,
        "playtime_at_review_hours": 72.1,
        "created_date": "2025-11-09 08:15:00",
        "timestamp_created": 1731141300,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1003",
        "language": "schinese",
        "language_name": "简体中文",
        "review_text": "游戏画面很好，战斗系统也不错。但是服务器延迟太高了，经常掉线。希望能增加亚洲服务器。内容也比较少，需要更多更新。",
        "recommended": False,
        "votes_up": 88,
        "votes_funny": 3,
        "playtime_total_hours": 12.4,
        "playtime_at_review_hours": 10.2,
        "created_date": "2025-11-08 22:45:00",
        "timestamp_created": 1731107100,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1004",
        "language": "japanese",
        "language_name": "日本語",
        "review_text": "グラフィックは素晴らしいですが、コンテンツが少なすぎます。2週間でほぼ全てクリアしてしまいました。もっとエンドゲームコンテンツが必要です。",
        "recommended": False,
        "votes_up": 34,
        "votes_funny": 1,
        "playtime_total_hours": 28.7,
        "playtime_at_review_hours": 25.3,
        "created_date": "2025-11-07 18:20:00",
        "timestamp_created": 1731005000,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1005",
        "language": "korean",
        "language_name": "한국어",
        "review_text": "무료 게임치고는 퀄리티가 좋습니다. 그래픽도 예쁘고 조작감도 괜찮아요. 근데 최적화가 좀 아쉬워요. 고사양 컴퓨터인데도 프레임 드랍이 있어요. 그래도 추천!",
        "recommended": True,
        "votes_up": 56,
        "votes_funny": 0,
        "playtime_total_hours": 34.2,
        "playtime_at_review_hours": 30.0,
        "created_date": "2025-11-06 12:00:00",
        "timestamp_created": 1730894400,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1006",
        "language": "english",
        "language_name": "English",
        "review_text": "The combat is fantastic, best-in-class shooting mechanics. But the lack of content is killing this game. No endgame, no reason to keep playing after 20 hours. Devs need to add more missions ASAP.",
        "recommended": False,
        "votes_up": 203,
        "votes_funny": 8,
        "playtime_total_hours": 45.6,
        "playtime_at_review_hours": 42.1,
        "created_date": "2025-11-05 16:30:00",
        "timestamp_created": 1730825400,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1007",
        "language": "russian",
        "language_name": "Русский",
        "review_text": "Отличная игра! Графика супер, геймплей затягивает. Играю с друзьями каждый день. Единственный минус - мало контента, но разработчики обещают обновления.",
        "recommended": True,
        "votes_up": 67,
        "votes_funny": 2,
        "playtime_total_hours": 78.9,
        "playtime_at_review_hours": 65.4,
        "created_date": "2025-11-04 20:15:00",
        "timestamp_created": 1730750100,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1008",
        "language": "german",
        "language_name": "Deutsch",
        "review_text": "Gutes Spiel, macht Spaß mit Freunden. Die Grafik ist wunderschön. Aber es gibt zu wenig Inhalt und die Server sind manchmal instabil. Hoffe auf Updates!",
        "recommended": True,
        "votes_up": 28,
        "votes_funny": 0,
        "playtime_total_hours": 23.4,
        "playtime_at_review_hours": 20.1,
        "created_date": "2025-11-03 14:45:00",
        "timestamp_created": 1730644500,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1009",
        "language": "english",
        "language_name": "English",
        "review_text": "Performance issues are terrible. Constant stuttering, frame drops, and crashes. I have a RTX 4080 and still can't run this smoothly. The game itself seems fun but it's unplayable in its current state.",
        "recommended": False,
        "votes_up": 445,
        "votes_funny": 12,
        "playtime_total_hours": 8.2,
        "playtime_at_review_hours": 6.5,
        "created_date": "2025-11-02 09:00:00",
        "timestamp_created": 1730537200,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1010",
        "language": "korean",
        "language_name": "한국어",
        "review_text": "솔직히 콘텐츠 부족이 너무 심해요. 출시 2주만에 할 게 없어졌어요. 전투는 재밌는데 반복되는 미션만 계속 해야 해서 지루해요. 업데이트 없으면 접을 것 같아요.",
        "recommended": False,
        "votes_up": 89,
        "votes_funny": 4,
        "playtime_total_hours": 52.3,
        "playtime_at_review_hours": 48.7,
        "created_date": "2025-11-01 21:30:00",
        "timestamp_created": 1730495400,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1011",
        "language": "english",
        "language_name": "English",
        "review_text": "This is what Anthem should have been. Incredible visuals, smooth gameplay, and fun co-op. Yes, it needs more content, but the foundation is solid. Definitely recommend for free-to-play!",
        "recommended": True,
        "votes_up": 312,
        "votes_funny": 15,
        "playtime_total_hours": 56.7,
        "playtime_at_review_hours": 50.2,
        "created_date": "2025-10-31 17:00:00",
        "timestamp_created": 1730393200,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1012",
        "language": "french",
        "language_name": "Français",
        "review_text": "Excellent jeu gratuit! Les graphismes sont magnifiques et le gameplay est fluide. Le système de combat est vraiment satisfaisant. J'attends plus de contenu avec impatience.",
        "recommended": True,
        "votes_up": 41,
        "votes_funny": 1,
        "playtime_total_hours": 33.8,
        "playtime_at_review_hours": 28.5,
        "created_date": "2025-10-30 13:20:00",
        "timestamp_created": 1730293200,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1013",
        "language": "english",
        "language_name": "English",
        "review_text": "The looting system is boring. All the weapons feel the same, no exciting drops. Compared to Destiny or Division, the loot is extremely disappointing. Combat is good but loot needs major improvement.",
        "recommended": False,
        "votes_up": 178,
        "votes_funny": 6,
        "playtime_total_hours": 38.4,
        "playtime_at_review_hours": 35.2,
        "created_date": "2025-10-30 10:15:00",
        "timestamp_created": 1730282100,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1014",
        "language": "korean",
        "language_name": "한국어",
        "review_text": "난이도 밸런스가 이상해요. 초반은 너무 쉽고 후반은 갑자기 어려워져요. 솔로 플레이는 거의 불가능하고 무조건 파티가 필요해요. 밸런스 패치 필요합니다.",
        "recommended": False,
        "votes_up": 67,
        "votes_funny": 3,
        "playtime_total_hours": 41.2,
        "playtime_at_review_hours": 38.9,
        "created_date": "2025-10-29 19:45:00",
        "timestamp_created": 1730230500,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
    {
        "review_id": "1015",
        "language": "english",
        "language_name": "English",
        "review_text": "Amazing graphics, smooth 60fps on my mid-range PC. The movement and gunplay feel incredible. Playing this reminds me of the best parts of Warframe. Highly recommended!",
        "recommended": True,
        "votes_up": 234,
        "votes_funny": 7,
        "playtime_total_hours": 95.6,
        "playtime_at_review_hours": 80.3,
        "created_date": "2025-10-28 15:30:00",
        "timestamp_created": 1730128200,
        "steam_purchase": True,
        "received_for_free": False,
        "written_during_early_access": False,
    },
]

# 통계 정보
SAMPLE_STATISTICS = {
    "total_reviews": 15,
    "positive_reviews": 9,
    "negative_reviews": 6,
    "positive_rate": 60.0,
    "negative_rate": 40.0,
    "average_playtime_hours": 47.1,
    "language_distribution": {
        "English": 6,
        "한국어": 4,
        "简体中文": 1,
        "日本語": 1,
        "Русский": 1,
        "Deutsch": 1,
        "Français": 1
    }
}

def get_sample_data():
    """샘플 크롤링 결과 반환"""
    return {
        "success": True,
        "game_info": SAMPLE_GAME_INFO,
        "reviews": SAMPLE_REVIEWS,
        "statistics": SAMPLE_STATISTICS,
        "crawl_info": {
            "requested_count": 15,
            "actual_count": 15,
            "day_range": 14,
            "crawled_at": "2025-01-23T12:00:00",
        }
    }
